### PR TITLE
improve some translations of WMF README and WMF 5.1 compatibility.

### PR DESCRIPTION
**Pull request by stknohg**
changed "箱で出荷" to "出荷時にインストール済み".
changed "はい" to "可".

Is this Pull Request #4 regression? or my Pull Request was rejected?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs.ja-jp/6)

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/compatibility.md](https://github.com/stknohg/powerShell-Docs.ja-jp/blob/patch004/wmf/5.1/compatibility.md) | :warning:Warning | | [Details](#user-content-wmf/5.1/compatibility.md)
[wmf/README.md](https://github.com/stknohg/powerShell-Docs.ja-jp/blob/patch004/wmf/README.md) | :warning:Warning | | [Details](#user-content-wmf/README.md)

<a name="wmf/5.1/compatibility.md"></a>
### [wmf/5.1/compatibility.md](https://github.com/stknohg/powerShell-Docs.ja-jp/blob/patch004/wmf/5.1/compatibility.md)
 - **[Warning]** the value HT is undefined for metadata translationtype

<a name="wmf/README.md"></a>
### [wmf/README.md](https://github.com/stknohg/powerShell-Docs.ja-jp/blob/patch004/wmf/README.md)
 - **[Warning]** the value HT is undefined for metadata translationtype

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C7%5Ce4718be7-89cf-ec1d-7c65-f7edcf9df322%5CPullRequest%5C201703070944235435-6%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @stknohg , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@stknohg , Thank you for your feedback and suggestion! 
		
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
		
Microsoft C&E Localization Team

**Comment by stknohg** [comment]
@gosali Thank you!

**Pull request merged**
